routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// ===============================================
// STATIC PAGES ==================================
// ===============================================

// Display all resources on the map
Route::get('/', 'RouteController@all');

// About page
Route::view('/about', 'pages/about');

// Features page
Route::view('/features', 'pages/features');

// ===============================================
// PUBLIC ROUTES PAGES ====================================
// ===============================================

// Display resources on the map
Route::get('/routes/all', 'RouteController@all');

// Display the specified resource on the map
Route::get('/routes/{id}', 'RouteController@show');

// Display a listing of the resources
Route::get('/routes', 'RouteController@index');

// ===============================================
// POINTS PAGES ==================================
// ===============================================

// Display a listing of the resources
Route::get('points', 'GooglePointController@index');

// Display resources on the map
Route::get('points/all', 'GooglePointController@all');
Route::post('points/ajaxgetinfo', 'AjaxController@getPointInfo');

// Show category of points
Route::get('points/{id}', 'GooglePointController@show');

// Display the specified resource on the map
Route::get('points/{cat}/{id}', 'RoutePointsController@showPointOnMap');

// ===============================================
// USER AREA =====================================
// ===============================================

Route::prefix('user')->group(function () {
    Auth::routes();

    Route::get('routes/all', 'RouteController@all')->middleware('auth');
    Route::resource('routes', 'RouteController')->middleware('auth');

    Route::get('points/all', 'GooglePointController@all')->middleware('auth');
    Route::post('points/ajaxgetinfo', 'AjaxController@getPointInfo')->middleware('auth');
    Route::resource('points', 'GooglePointController')->middleware('auth');
});

app/Route.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Route extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['user_id','name','description','category','distance','min_alt','max_alt','elevation_gain','duration'];

    /**
     * Get the points for the route.
     */
    public function points()
    {
        return $this->hasMany('App\RoutePoints', 'route_id', 'id');
    }

    /**
     * Get distance.
     *
     * @param  integer $value
     * @return integer
     */
    public function getDistanceAttribute($value)
    {
        $distance = number_format($value / 1000, 1);
        return $distance;
    }

    /**
     * Get description.
     *
     * @param  string $value
     * @return string
     */
    public function getDescriptionAttribute($value)
    {
        $description = str_replace('\'','"', $value);
        $description = str_replace(["\n", "\r"], '', $description);
        return $description;
    }

    /**
     * Get time.
     *
     * @param  integer $value
     * @return string
     */
    public function getDurationAttribute($value)
    {
        if($value !== null) {
            $hours = floor($value / 3600);
            $minutes = floor(($value / 60) % 60);
            $seconds = $value % 60;

            return "$hours:$minutes:$seconds";
        }

        return $value;
    }

    /**
     * Scope a query to only include public and visible resources.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopePublic($query)
    {
        return $query->where('public', 1);
    }

    /**
     * Scope a query to only include private resources.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopePrivate($query)
    {
        return $query->where('user_id', Auth::id());
    }
}

app/Http/Controllers/RouteController.php
<?php

namespace App\Http\Controllers;

use App\Route;
use App\RoutePoints;
use Illuminate\Http\Request;
use phpGPX\Models\Point;
use phpGPX\phpGPX;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Mapper;
use App\Http\Traits\GisFunction;

class RouteController extends Controller
{
    use GisFunction;
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $prefix = $request->route()->getPrefix();
        if ($prefix == '/user') {
            $routes = Route::where('user_id', Auth::id())->paginate(30);
            return view('pages.route.user-routes-index', compact('routes'));
        } else {
            $routes = Route::where('public', '1')->paginate(30);
            return view('pages.route.public-routes-index', compact('routes'));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        Mapper::map(53.250981071172895, 50.265240499999976, ['zoom' => 10, 'center' => true, 'setmarker' => true]);

        return view('pages.route.user-route-create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:255',
            'file' => 'required|file|max:1024'
        ]);

        $gpx = new phpGPX();
        $file = $gpx->load($request->file);

        foreach ($file->tracks as $track) {
            $stat = $track->stats->toArray();

            $data_route = [
                'user_id' => Auth::id(),
                'name' => $request->get('name'),
                'description' => $request->get('description'),
                'distance' => intval($stat['distance']),
                'min_alt' => $stat['minAltitude'],
                'max_alt' => $stat['maxAltitude'],
                'elevation_gain' => $stat['cumulativeElevationGain'],
                'duration' => $stat['duration']
            ];

            $route = new Route($data_route);
            $route->save();

            $points = $track->getPoints();

            foreach ($points as $point) {
                $data_points[] = [
                    'route_id' => $route->id,
                    'coordinates' => DB::raw("GeomFromText('POINT(" . $point->latitude . " " . $point->longitude . ")')"),
                    'altitude' => $point->elevation,
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ];
            }

            RoutePoints::insert($data_points);
        }

        return redirect('/user/routes/'. $route->id)->with('success', 'Трек сохранен');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id, Request $request)
    {
        $prefix = $request->route()->getPrefix();
        if ($prefix == '/user') {
            $route = Route::with('points')->where('user_id', Auth::id())->findOrFail($id);
            $points = $route->points;

            // get first point and show the map
            Mapper::map($points[0]->lat, $points[0]->lng, ['center' => true]);

            // Get polyline and nearest points (<=2000m)
            $polyline = $this->getPolylines($route);
            $nearestPoints = $this->getNearestPoints($points, 10, 2000);

            //echo count($polyline);
            //echo '<pre>';
            //print_r($polyline);
            //die;

            $data = [
                'id' => $route->id,
                'name' => $route->name,
                'description' => $route->description,
                'distance' => $route->distance,
                'elevation_gain' => $route->elevation_gain,
                'path' => '/user/routes'
            ];

            Mapper::polyline($polyline, ['data' => $data]);

            foreach ($nearestPoints as $nearestPoint) {
                Mapper::informationWindow($nearestPoint['lat'], $nearestPoint['lng'], $nearestPoint, ['markers' => []]);
            }

            return view('pages.route.user-route-show', compact('route'));
        } else {
            $route = Route::with('points')->findOrFail($id);

            $points = $route->points;

            // get first point and show the map
            Mapper::map($points[0]->lat, $points[0]->lng, ['center' => true]);

            // Get polyline and nearest points (<=2000m)
            $polyline = $this->getPolylines($route);
            $nearestPoints = $this->getNearestPoints($points, 10, 2000);

            $data = [
                'id' => $route->id,
                'name' => $route->name,
                'description' => $route->description,
                'distance' => $route->distance,
                'elevation_gain' => $route->elevation_gain,
                'path' => '/routes'
            ];

            Mapper::polyline($polyline, ['data' => $data]);

            foreach ($nearestPoints as $nearestPoint) {
                Mapper::informationWindow($nearestPoint['lat'], $nearestPoint['lng'], $nearestPoint, ['markers' => []]);
            }

            return view('pages.route.public-route-show', compact('route'));
        }


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $route = Route::find($id);

        return view('pages.route.user-route-edit', compact('route'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->has('change-access') && $request->has('public')) {
            $request->validate(['public' => 'numeric']);

            $route = Route::private()->findOrFail($id);
            $route->public = $request->get('public');
            $route->save();

            return redirect('/user/routes')->with('success', 'Данные успешно изменены');
        }

        $request->validate([
            'name' => 'required|max:255'
        ]);

        $route = Route::find($id);
        $route->name = $request->get('name');
        $route->description = $request->get('description');
        $route->save();

        return redirect('/user/routes')->with('success', 'Информация успешно изменена');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $points = RoutePoints::where('route_id', $id)->delete();
        $route = Route::find($id)->delete();

        return redirect('/user/routes')->with('success', 'Трек успешно удален');
    }

    /**
     * Display all resources on the map.
     *
     * @return \Illuminate\Http\Response
     */
    public function all(Request $request)
    {
        Mapper::map(53.250981071172895, 50.265240499999976, ['zoom' => 10, 'center' => true]);

        $prefix = $request->route()->getPrefix();
        if ($prefix == '/user') {
            $routes = Route::with('points')->private()->get();

            foreach ($routes as $route) {
                $polyline = $this->getPolylines($route);
                $color = '#' . dechex(rand(256,16777215)); // Polyline color

                $data = [
                    'id' => $route->id,
                    'name' => $route->name,
                    'description' => $route->description,
                    'distance' => $route->distance,
                    'elevation_gain' => $route->elevation_gain,
                    'path' => '/user/routes'
                ];
                Mapper::polyline($polyline, ['strokeColor' => $color, 'strokeWeight' => 3, 'data' => $data]);
            }

            return view('pages.route.user-routes-all');
        } else {
            $routes = Route::with('points')->public()->get();

            foreach ($routes as $route) {
                $polyline = $this->getPolylines($route);
                $color = '#' . dechex(rand(256,16777215)); // Polyline color

                $data = [
                    'id' => $route->id,
                    'name' => $route->name,
                    'description' => $route->description,
                    'distance' => $route->distance,
                    'elevation_gain' => $route->elevation_gain,
                    'path' => '/routes'
                ];

                Mapper::polyline($polyline, ['strokeColor' => $color, 'strokeWeight' => 3, 'data' => $data]);
            }

            return view('pages.route.public-routes-all');
        }
    }
}

resources/views/pages/route/public-route-show.blade.php
@extends('layouts.default')

@section('content')
    <article class="content responsive-tables-page" style="position:relative;padding: 70px 0 0 0;">
        <div id="map_canvas">
            {!! Mapper::render() !!}
        </div>
        <div id="trek_info">
            <div class="card card-info">
                <div class="card-header">
                    <div class="header-block">
                        <div class="title">
                            @if(session()->get('success'))
                                {{ session()->get('success') }}
                            @else
                                Информация
                            @endif
                            <span class="pull-right trek_menu"><i
                                    class="fa fa-minus-square" aria-hidden="true"></i></span></div>
                    </div>
                </div>
                <div class="card-block">
                    <div class="form-group">
                        <label class="control-label bolder">Название:</label>
                        <input disabled="disabled" type="text" name="name" class="form-control boxed" value="{{ $route->name }}">
                        <span class="has-error" style="display: none;">Заполните поле</span>
                    </div>
                    @if ($route->description)
                        <div class="form-group">
                            <label class="control-label">Описание:</label>
                            <textarea disabled="disabled" rows="3" name="description" class="form-control boxed">{{ $route->description }}</textarea>
                        </div>
                    @endif
                    <div class="form-group">
                        <label class="control-label">Дистанция(км):</label>
                        <input type="text" id="distance" name="distance" readonly="readonly" class="form-control boxed" value="{{ $route->distance }}">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Набор высоты(м):</label>
                        <input type="text" id="elevation_gain" name="elevation_gain" readonly="readonly" class="form-control boxed" value="{{ $route->elevation_gain }}">
                    </div>
                    @if ($route->duration)
                        <div class="form-group">
                            <label class="control-label">Время:</label>
                            <input type="text" id="duration" name="duration" readonly="readonly" class="form-control boxed" value="{{ $route->duration }}">
                        </div>
                    @endif
                    <hr>
                    <a href="/routes">К списку треков</a>
                </div>
            </div>
        </div>
    </article>
@stop

resources/views/pages/route/user-route-create.blade.php
@extends('layouts.default')

@section('content')
    <article class="content responsive-tables-page" style="position:relative;padding: 70px 0 0 0;">
        <div id="map_canvas">
            {!! Mapper::render() !!}
        </div>
        <div id="trek_info">
            <div class="card card-info">
                <div class="card-header">
                    <div class="header-block">
                        <div class="title"> Информация <span class="pull-right trek_menu"><i
                                        class="fa fa-minus-square" aria-hidden="true"></i></span></div>
                    </div>
                </div>
                <div class="card-block">
                    <form action="{{ route('routes.store') }}" method="post" id="create_route" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label class="control-label">Файл(.gpx):</label>
                            <input id="file" type="file" name="file" class="form-control-file" value="">
                        </div>
                        <div class="form-group">
                            <label class="control-label bolder">Название *:</label>
                            <input id="name" type="text" name="name" class="form-control boxed">
                            <span class="has-error" style="display: none;">Заполните поле</span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Описание:</label>
                            <textarea id="description" rows="3" name="description" class="form-control boxed"></textarea>
                        </div>
                        <hr>
                        <button type="submit" class="btn btn-success">Сохранить</button>
                        <button type="button" class="btn btn-danger" id="delete_marker">Очистить</button>
                        <a href="/user/routes" style="float:right;">Назад</a>
                    </form>
                </div>
            </div>
        </div>
    </article>
@stop

resources/views/pages/route/user-route-edit.blade.php
@extends('layouts.default')

@section('content')
    <article class="content typography-page">
        <div class="title-block">
            <h3 class="title"> Редактирование</h3>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @if ($message = Session::get('success'))
            <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                {{ $message }}
            </div>

        @endif

        <form action="{{ route('routes.update', $route->id) }}" method="post">
            @csrf
            @method('PUT')
            <div class="card card-block">
                <div class="form-group row">
                    <label class="col-sm-2 form-control-label text-xs-right"> Название: </label>
                    <div class="col-sm-10">
                        <input type="text" name="name" value="{{ $route->name }}" class="form-control boxed" placeholder="">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 form-control-label text-xs-right"> Описание: </label>
                    <div class="col-sm-10">
                        <textarea rows="5" name="description" class="form-control boxed">{{ $route->description }}</textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10 col-sm-offset-2">
                        <button type="submit" class="btn btn-primary"> Отправить </button>
                    </div>
                </div>
            </div>
        </form>
    </article>
@stop

resources/views/pages/route/user-routes-index.blade.php
@extends('layouts.default')

@section('content')
    <article class="content responsive-tables-page">
        <div class="title-block">
            <h1 class="title"> Мои треки </h1>
            <p class="title-description"> Добавьте свой трек в формате gpx </p>
        </div>
        <p>
            <a href="/user/routes/create" class="btn btn-primary">Добавить трек</a>
            <a href="/user/routes/all" class="btn btn-success">Показать на карте</a>
        </p>
        @if(session()->get('success'))
            <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                {{ session()->get('success') }}
            </div>
        @endif
        <section class="section">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-block">
                            <div class="card-title-block">
                                <h3 class="title"> Список треков </h3>
                            </div>
                            <section class="example">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-hover">
                                        <thead>
                                        <tr>
                                            <th class="align-middle text-left">Название</th>
                                            <th class="align-middle text-center">Длина(км)</th>
                                            <th class="align-middle text-center">Мин.высота(м)</th>
                                            <th class="align-middle text-center">Макс.высота(м)</th>
                                            <th class="align-middle text-center">Набор высоты(м)</th>
                                            <th class="align-middle text-center">Время(ч)</th>
                                            <th class="align-middle text-center">Действия</th>
                                            <th class="align-middle text-center">Статус</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach ($routes as $route)
                                            <tr>
                                                <td><a href="/user/routes/{{ $route->id }}">{{ $route->name }}</a></td>
                                                <td class="text-center">
                                                    @if ($route->distance)
                                                        {{ $route->distance }}
                                                    @else
                                                        -
                                                    @endif
                                                </td>
                                                <td class="text-center">
                                                    @if ($route->min_alt)
                                                        {{ $route->min_alt }}
                                                    @else
                                                        -
                                                    @endif
                                                </td>
                                                <td class="text-center">
                                                    @if ($route->max_alt)
                                                        {{ $route->max_alt }}
                                                    @else
                                                        -
                                                    @endif
                                                </td>
                                                <td class="text-center">
                                                    @if ($route->elevation_gain)
                                                        {{ $route->elevation_gain }}
                                                    @else
                                                        -
                                                    @endif
                                                </td>
                                                <td class="text-center">
                                                    @if ($route->duration)
                                                        {{ $route->duration }}
                                                    @else
                                                        -
                                                    @endif
                                                </td>
                                                <td class="text-center" style="width: 100px;">
                                                    <div class="btn-group dropleft">
                                                        <i id="actions" class="fa fa-cog" aria-hidden="true"
                                                           data-toggle="dropdown" aria-haspopup="true"
                                                           aria-expanded="false"></i>
                                                        <div class="dropdown-menu">
                                                            <a href="/user/routes/{{ $route->id }}/edit" alt="изменить"
                                                               title="изменить" class="dropdown-item">Изменить</a>
                                                            <form action="{{ route('routes.update', $route->id)}}" method="post" id="actions-form">
                                                                @csrf
                                                                @method('PATCH')
                                                                @if ($route->public == 0)
                                                                    <input name="public" type="hidden" value="1">
                                                                    <input name="change-access" type="hidden" value="1">
                                                                    <button style="cursor: pointer;" class="dropdown-item" type="submit">Общий доступ</button>
                                                                @elseif ($route->public == 1)
                                                                    <input name="public" type="hidden" value="0">
                                                                    <input name="change-access" type="hidden" value="0">
                                                                    <button style="cursor: pointer;" class="dropdown-item" type="submit">Приватный</button>
                                                                @endif
                                                            </form>
                                                            <button type="button" style="cursor: pointer;"
                                                                    class="dropdown-item destroy"
                                                                    data-route="{{ route('routes.destroy', $route->id)}}"
                                                                    data-toggle="modal" data-target="#modal-actions">
                                                                Удалить
                                                            </button>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td class="text-center">
                                                    @if ($route->public == 1)
                                                        <i class="fa fa-share-alt" aria-hidden="true"
                                                           title="Общий доступ"></i>
                                                    @elseif ($route->public == 0)
                                                        <i class="fa fa-lock" aria-hidden="true" title="Приватный"></i>
                                                    @endif
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    {{ $routes->links() }}
                                </div>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </article>

    <!-- Modal -->
    <div class="modal fade" id="modal-actions" tabindex="-1" role="dialog"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Удалить элемент</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                </div>
                <div class="modal-body">
                    Уверены, что хотите удалить элемент?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>
                    <form action="" method="post" id="actions-form">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit">Да</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop