routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// ===============================================
// STATIC PAGES ==================================
// ===============================================

// Display all resources on the map
Route::get('/', 'RouteController@all');

// About page
Route::view('/about', 'pages/about');

// Features page
Route::view('/features', 'pages/features');

// ===============================================
// PUBLIC ROUTES PAGES ====================================
// ===============================================

// Display resources on the map
Route::get('/routes/all', 'RouteController@all');

// Display the specified resource on the map
Route::get('/routes/{id}', 'RouteController@show');

// Display a listing of the resources
Route::get('/routes', 'RouteController@index');

// ===============================================
// POINTS PAGES ==================================
// ===============================================

// Display a listing of the resources
Route::get('points', 'GooglePointController@index');

// Display resources on the map
Route::get('points/all', 'GooglePointController@all');
Route::post('points/ajaxgetinfo', 'AjaxController@getPointInfo');

// Show category of points
Route::get('points/{id}', 'GooglePointController@show');

// Display the specified resource on the map
Route::get('points/{cat}/{id}', 'RoutePointsController@showPointOnMap');

// ===============================================
// USER AREA =====================================
// ===============================================

Route::prefix('user')->group(function () {
    Auth::routes();

    Route::get('routes/all', 'RouteController@all')->middleware('auth');
    Route::resource('routes', 'RouteController')->middleware('auth');

    Route::get('points/all', 'GooglePointController@all')->middleware('auth');
    Route::post('points/ajaxgetinfo', 'AjaxController@getPointInfo')->middleware('auth');
    Route::resource('points', 'GooglePointController')->middleware('auth');
});

app/Http/Controllers/RoutePointsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\CatPoints;
use App\GooglePoint;
use Mapper;
use App\Http\Traits\GisFunction;

class RoutePointsController extends Controller
{
    use GisFunction;

    /**
     * Display a listing of the resources
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $categories = CatPoints::withCount('points')->get();

        return view('pages.point.points-page', compact('categories'));
    }

    /**
     * Show category of points
     *
     * @param  int $id
     * @return \Illuminate\View\View
     */
    public function showPointsCat($id)
    {
        $catName = CatPoints::find($id);
        $pointslist = GooglePoint::where('category_id', $id)->get();

        return view('pages.point.points-cat-page')->with('pointslist', $pointslist)->with('catname', $catName);
    }

    /**
     * Display the specified resource on the map
     *
     * @param $id
     * @return \Illuminate\View\View
     */
    public function showPointOnMap($cat, $id, Request $request)
    {
        $point = GooglePoint::find($id);
        $category = CatPoints::find($cat);

        //dd($point->toArray());

        Mapper::map($point->lat, $point->lng, ['zoom' => 11, 'center' => true]);
        Mapper::informationWindow($point->lat, $point->lng, $point->toArray());

        if ($request->input('show') && $request->input('show') == 'routes') {
            $routes = $this->getNearestRoutes($point, 2000); // 2000 meters

            foreach ($routes as $route) {
                $polyline = $this->getPolylines($route);

                // Polyline color generation
                $color = sprintf('#%06X', mt_rand(0, 0xFFFFFF));

                $data = [
                    'id' => $route->id,
                    'name' => $route->name,
                    'description' => $route->description,
                    'distance' => $route->distance
                ];

                Mapper::polyline($polyline, ['strokeColor' => $color, 'strokeWeight' => 3, 'data' => $data]);
            }
        }

        return view('pages.point.point-map', ['point' => $point, 'category' => $category]);
    }
}

resources/views/pages/point/point-map.blade.php
@extends('layouts.default')

@section('content')
    <article class="content responsive-tables-page" style="position:relative;padding: 70px 0 0 0;">
        <div id="map_canvas">
            {!! Mapper::render() !!}
        </div>
        <div id="trek_info">
            <div class="card card-info">
                <div class="card-header">
                    <div class="header-block">
                        <div class="title"> {{ $point->vcName }} <span class="pull-right trek_menu"><i
                                        class="fa fa-minus-square" aria-hidden="true"></i></span></div>
                    </div>
                </div>
                <div class="card-block">
                    <p>Категория: <a href="/points/{{ $category->vcCategory_id }}">{{ $category->name }}</a></p>
                    <p>Координаты: {{ $point->lat }}, {{ $point->lng }}</p>
                    <p>Описание:
                        @if(empty($point->vcDescription))
                            отсутствует
                        @else
                            {{ $point->vcDescription }}
                        @endif
                    </p>
                    <hr>
                    <p><a href="{{url()->current()}}?show=routes">Ближайшие к точке треки</a></p>
                    <p><a href="{{ url()->previous() }}">Вернуться назад</a></p>
                </div>
            </div>
        </div>
    </article>
@stop

resources/views/pages/point/points-cat-page.blade.php
@extends('layouts.default')

@section('content')
    <article class="content responsive-tables-page">
        <div class="title-block">
            <h1 class="title"> Точки </h1>
            <p class="title-description"> Выберите интересующую категорию или воспользуйтесь поиском </p>
        </div>
        <section class="section">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-block">
                            <div class="card-title-block">
                                <h3 class="title"> Категория "{{ $catname->name }}"</h3>
                            </div>
                            <section class="example">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-hover">
                                        <thead>
                                        <tr>
                                            <th class="align-middle">Название</th>
                                            <th class="align-middle">Координаты</th>
                                            <th class="align-middle">Ближайшие треки</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach ($pointslist as $point)
                                            <tr>
                                                <td>
                                                    <a href="/points/{{ $point->vcCategory_id }}/{{ $point->GoogleMapPointID }}">{{ $point->vcName }}</a>
                                                    @if ($point->vcDescription)
                                                        <br>
                                                        <small>{!! $point->vcDescription !!}</small>
                                                    @endif
                                                </td>
                                                <td>
                                                    {{ $point->lat }}
                                                    <br>
                                                    {{ $point->lng }}
                                                </td>
                                                <td></td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </article>
@stop

resources/views/pages/point/points-page.blade.php
@extends('layouts.default')

@section('content')
    <article class="content responsive-tables-page">
        <div class="title-block">
            <h1 class="title"> Точки </h1>
            <p class="title-description"> Выберите интересующую категорию или воспользуйтесь поиском </p>
        </div>
        <section class="section">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-block">
                            <div class="card-title-block">
                                <h3 class="title"> Категории точек </h3>
                            </div>
                            <section class="example">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-hover">
                                        <thead>
                                        <tr>
                                            <th class="align-middle">Категория</th>
                                            <th class="align-middle">Количество</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach ($categories as $category)
                                            <tr>
                                                <td><a href="/points/{{ $category->vcCategory_id }}">{{ $category->name }}</a></td>
                                                <td>{{ $category->points_count }}</td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </article>
@stop

resources/views/pages/point/public-point-show.blade.php
@extends('layouts.default')

@section('content')
    <article class="content responsive-tables-page" style="position:relative;padding: 70px 0 0 0;">
        <div id="map_canvas">
            {!! Mapper::render() !!}
        </div>
        <div id="trek_info">
            <div class="card card-info">
                <div class="card-header">
                    <div class="header-block">
                        <div class="title"> Информация <span class="pull-right trek_menu"><i
                                        class="fa fa-minus-square" aria-hidden="true"></i></span></div>
                    </div>
                </div>
                <div class="card-block">
                    <div class="form-group">
                        <label class="control-label bolder">Название:</label>
                        <input disabled="disabled" type="text" name="name" class="form-control boxed" value="{{ $point->name }}">
                        <span class="has-error" style="display: none;">Заполните поле</span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Описание:</label>
                        <textarea disabled="disabled" rows="3" name="description" class="form-control boxed">{{ $point->description }}</textarea>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Высота:</label>
                        <input type="text" id="altitude" name="altitude" readonly="readonly" class="form-control boxed" value="{{ $point->altitude }}">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Координаты:</label>
                        <input type="text" id="lat" name="lat" disabled="disabled" class="form-control boxed" value="{{ $point->lat }}"> <br>
                        <input type="text" id="lng" name="lng" disabled="disabled" class="form-control boxed" value="{{ $point->lng }}">
                        <span class="has-error" style="display: none;">Укажите точку</span>
                    </div>
                    <hr>
                    <a href="/user/points">Назад</a>
                </div>
            </div>
        </div>
    </article>
@stop

resources/views/pages/point/public-points-all.blade.php
@extends('layouts.default')

@section('content')
    <article class="content responsive-tables-page" style="position:relative;padding: 70px 0 0 0;">
        <div id="map_canvas">
            {!! Mapper::render() !!}
        </div>
        <div id="trek_info">
            <div class="card card-info">
                <div class="card-header">
                    <div class="header-block">
                        <div class="title"> Информация <span class="pull-right trek_menu"><i
                                        class="fa fa-minus-square" aria-hidden="true"></i></span></div>
                    </div>
                </div>
                <div class="card-block">
                    <div class="form-group">
                        <label class="control-label bolder">Название:</label>
                        <input disabled="disabled" type="text" name="name" class="form-control boxed" value="">
                        <span class="has-error" style="display: none;">Заполните поле</span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Описание:</label>
                        <textarea disabled="disabled" rows="3" name="description" class="form-control boxed"></textarea>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Высота:</label>
                        <input type="text" id="altitude" name="altitude" readonly="readonly" class="form-control boxed" value="">
                    </div>
                    <div class="form-group">
                        <label class="control-label">Координаты:</label>
                        <input type="text" id="lat" name="lat" disabled="disabled" class="form-control boxed" value=""> <br>
                        <input type="text" id="lng" name="lng" disabled="disabled" class="form-control boxed" value="">
                        <span class="has-error" style="display: none;">Укажите точку</span>
                    </div>
                    <hr>
                    <a href="/points">Назад</a>
                </div>
            </div>
        </div>
    </article>
@stop

resources/views/pages/point/user-point-create.blade.php
@extends('layouts.default')

@section('content')
    <article class="content responsive-tables-page" style="position:relative;padding: 70px 0 0 0;">
        <div id="map_canvas">
            {!! Mapper::render() !!}
        </div>
        <div id="trek_info">
            <div class="card card-info">
                <div class="card-header">
                    <div class="header-block">
                        <div class="title"> Информация <span class="pull-right trek_menu"><i
                                        class="fa fa-minus-square" aria-hidden="true"></i></span></div>
                    </div>
                </div>
                <div class="card-block">
                    <form action="{{ route('points.store') }}" method="post" id="create_point">
                        @csrf
                        <div class="form-group">
                            <label class="control-label bolder">Название *:</label>
                            <input id="name" type="text" name="name" class="form-control boxed">
                            <span class="has-error" style="display: none;">Заполните поле</span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Описание:</label>
                            <textarea id="description" rows="3" name="description" class="form-control boxed"></textarea>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Высота:</label>
                            <input id="altitude" type="text" name="altitude" readonly="readonly" class="form-control boxed" value="">
                            <span class="has-error" style="display: none;">Поле не может быть пустым</span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Координаты:</label>
                            <input id="lat" type="text" name="lat" readonly="readonly" class="form-control boxed" value=""> <br>
                            <input id="lng" type="text" name="lng" readonly="readonly" class="form-control boxed" value="">
                            <span class="has-error" style="display: none;">Поля не могут быть пустыми</span>
                        </div>
                        <hr>
                        <button type="submit" class="btn btn-success">Сохранить</button>
                        <button type="button" class="btn btn-danger" id="delete_marker">Очистить</button>
                        <a href="/user/points" style="float:right;">Назад</a>
                    </form>
                </div>
            </div>
        </div>
    </article>
@stop

resources/views/pages/point/user-point-edit.blade.php
@extends('layouts.default')

@section('content')
    <article class="content responsive-tables-page" style="position:relative;padding: 70px 0 0 0;">
        <div id="map_canvas">
            {!! Mapper::render() !!}
        </div>
        <div id="trek_info">
            <div class="card card-info">
                <div class="card-header">
                    <div class="header-block">
                        <div class="title"> Информация <span class="pull-right trek_menu"><i
                                        class="fa fa-minus-square" aria-hidden="true"></i></span></div>
                    </div>
                </div>
                <div class="card-block">
                    <form action="{{ route('points.update', $point->id) }}" method="post" id="create_point">
                        @method('PATCH')
                        @csrf
                        <div class="form-group">
                            <label class="control-label bolder">Название *:</label>
                            <input type="text" name="name" class="form-control boxed" value="{{ $point->name }}">
                            <span class="has-error" style="display: none;">Заполните поле</span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Описание:</label>
                            <textarea rows="3" name="description" class="form-control boxed">{{ $point->description }}</textarea>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Высота:</label>
                            <input type="text" id="altitude" name="altitude" readonly="readonly" class="form-control boxed" value="{{ $point->altitude }}">
                        </div>
                        <div class="form-group">
                            <label class="control-label">Координаты:</label>
                            <input type="text" id="lat" name="lat" readonly="readonly" class="form-control boxed" value="{{ $point->lat }}"> <br>
                            <input type="text" id="lng" name="lng" readonly="readonly" class="form-control boxed" value="{{ $point->lng }}">
                            <span class="has-error" style="display: none;">Укажите точку</span>
                        </div>
                        <hr>
                        <button type="submit" class="btn btn-success">Сохранить</button>
                        <button type="button" class="btn btn-danger" id="delete_marker">Очистить</button>
                        <a href="/user/points" style="float:right;">Назад</a>
                    </form>
                </div>
            </div>
        </div>
    </article>
@stop

resources/views/pages/point/user-points-index.blade.php
@extends('layouts.default')

@section('content')
    <article class="content responsive-tables-page">
        <div class="title-block">
            <h1 class="title"> Мои точки </h1>
        </div>
        <p>
            <a href="/user/points/create" class="btn btn-primary">Добавить точку</a>
            <a href="/user/points/all" class="btn btn-success">Показать на карте</a>
        </p>
        @if(session()->get('success'))
            <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                {{ session()->get('success') }}
            </div>
        @endif
        <section class="section">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-block">
                            <div class="card-title-block">
                                <h3 class="title"> Список точек </h3>
                            </div>
                            <section class="">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-hover">
                                        <thead>
                                        <tr>
                                            <th class="align-middle text-center">#</th>
                                            <th class="align-middle text-left">Название</th>
                                            <th class="align-middle text-left">Описание</th>
                                            <th class="align-middle text-center">Координаты</th>
                                            <th class="align-middle text-center">Высота(м)</th>
                                            <th class="align-middle text-center">Действия</th>
                                            <th class="align-middle text-center">Статус</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach ($points as $k => $point)
                                            <tr>
                                                <td class="text-center">{{ $k+1 }}</td>
                                                <td><a href="/user/points/{{ $point->id }}">{{ $point->name }}</a></td>
                                                <td>{{ $point->description }}</td>
                                                <td class="text-center">
                                                    {{ $point->lat }}
                                                    <br>
                                                    {{ $point->lng }}
                                                </td>
                                                <td class="text-center">
                                                    @if ($point->altitude)
                                                        {{ $point->altitude }}
                                                    @else
                                                        -
                                                    @endif
                                                </td>
                                                <td class="text-center" style="width: 100px;">
                                                    <div class="btn-group dropleft">
                                                        <i id="actions" class="fa fa-cog" aria-hidden="true"
                                                           data-toggle="dropdown" aria-haspopup="true"
                                                           aria-expanded="false"></i>
                                                        <div class="dropdown-menu">
                                                            <a href="/user/points/{{ $point->id }}/edit" alt="изменить"
                                                               title="изменить" class="dropdown-item">Изменить</a>
                                                            <form action="{{ route('points.update', $point->id)}}" method="post" id="actions-form">
                                                                @csrf
                                                                @method('PATCH')
                                                                @if ($point->public == 0)
                                                                    <input name="public" type="hidden" value="1">
                                                                    <input name="change-access" type="hidden" value="1">
                                                                    <button style="cursor: pointer;" class="dropdown-item" type="submit">Общий доступ</button>
                                                                @elseif ($point->public == 1)
                                                                    <input name="public" type="hidden" value="0">
                                                                    <input name="change-access" type="hidden" value="0">
                                                                    <button style="cursor: pointer;" class="dropdown-item" type="submit">Приватный</button>
                                                                @endif
                                                            </form>
                                                            <button type="button" style="cursor: pointer;"
                                                                    class="dropdown-item destroy"
                                                                    data-route="{{ route('points.destroy', $point->id)}}"
                                                                    data-toggle="modal" data-target="#modal-actions">
                                                                Удалить
                                                            </button>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td class="text-center">
                                                    @if ($point->public == 1)
                                                        <i class="fa fa-share-alt" aria-hidden="true"
                                                           title="Общий доступ"></i>
                                                    @elseif ($point->public == 0)
                                                        <i class="fa fa-lock" aria-hidden="true" title="Приватный"></i>
                                                    @endif
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    {{ $points->links() }}
                                </div>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </article>

    <!-- Modal -->
    <div class="modal fade" id="modal-actions" tabindex="-1" role="dialog"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Удалить элемент</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                </div>
                <div class="modal-body">
                    Уверены, что хотите удалить элемент?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>
                    <form action="" method="post" id="actions-form">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit">Да</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop